package com.visnaa.gemstonepower.item.metal;

import com.visnaa.gemstonepower.init.ModBlocks;
import com.visnaa.gemstonepower.init.ModItems;
import net.minecraft.core.NonNullList;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;

import java.util.List;

public enum MetalGroups
{
    IRON(new MetalGroup(Items.IRON_INGOT, Blocks.IRON_BLOCK, Blocks.IRON_ORE, Blocks.DEEPSLATE_IRON_ORE, Items.RAW_IRON, Items.IRON_NUGGET, ModItems.IRON_DUST.get(), ModItems.IRON_TINY_PILE.get(), ModItems.IRON_ORE_DUST.get(), NonNullList.of(ModItems.IRON_DUST.get(), ModItems.IRON_DUST.get(), ModItems.RUBY.get()), ModItems.IRON_PLATE.get(), ModItems.IRON_ROD.get(), ModItems.IRON_GEAR.get(), null, null)),
    GOLD(new MetalGroup(Items.GOLD_INGOT, Blocks.GOLD_BLOCK, Blocks.GOLD_ORE, Blocks.DEEPSLATE_GOLD_ORE, Items.RAW_GOLD, Items.GOLD_NUGGET, ModItems.GOLD_DUST.get(), ModItems.GOLD_TINY_PILE.get(), ModItems.GOLD_ORE_DUST.get(), NonNullList.of(ModItems.GOLD_DUST.get(), ModItems.GOLD_DUST.get(), ModItems.NICKEL_TINY_PILE.get(), ModItems.SAPPHIRE.get()), ModItems.GOLD_PLATE.get(), ModItems.GOLD_ROD.get(), ModItems.GOLD_GEAR.get(), null, null)),
    COPPER(new MetalGroup(Items.COPPER_INGOT, Blocks.COPPER_BLOCK, Blocks.COPPER_ORE, Blocks.DEEPSLATE_COPPER_ORE, Items.RAW_COPPER, ModItems.COPPER_NUGGET.get(), ModItems.COPPER_DUST.get(), ModItems.COPPER_TINY_PILE.get(), ModItems.COPPER_ORE_DUST.get(), NonNullList.of(ModItems.COPPER_DUST.get(), ModItems.COPPER_DUST.get(), ModItems.SILVER_TINY_PILE.get(), ModItems.IRON_TINY_PILE.get(), ModItems.AQUAMARINE.get()), ModItems.COPPER_PLATE.get(), ModItems.COPPER_ROD.get(), ModItems.COPPER_GEAR.get(), ModBlocks.COPPER_WIRE.get(), ModBlocks.COPPER_CABLE.get())),
    ALUMINUM(new MetalGroup(ModItems.ALUMINUM_INGOT.get(), ModBlocks.ALUMINUM_BLOCK.get(), ModBlocks.ALUMINUM_ORE.get(), ModBlocks.DEEPSLATE_ALUMINUM_ORE.get(), ModItems.RAW_ALUMINUM.get(), ModItems.ALUMINUM_NUGGET.get(), ModItems.ALUMINUM_DUST.get(), ModItems.ALUMINUM_TINY_PILE.get(), ModItems.ALUMINUM_ORE_DUST.get(), NonNullList.of(ModItems.ALUMINUM_DUST.get(), ModItems.ALUMINUM_DUST.get(), ModItems.GOLD_TINY_PILE.get(), ModItems.JADE.get()), ModItems.ALUMINUM_PLATE.get(), ModItems.ALUMINUM_ROD.get(), ModItems.ALUMINUM_GEAR.get(), ModBlocks.ALUMINUM_WIRE.get(), ModBlocks.ALUMINUM_CABLE.get())),
    TIN(new MetalGroup(ModItems.TIN_INGOT.get(), ModBlocks.TIN_BLOCK.get(), ModBlocks.TIN_ORE.get(), ModBlocks.DEEPSLATE_TIN_ORE.get(), ModItems.RAW_TIN.get(), ModItems.TIN_NUGGET.get(), ModItems.TIN_DUST.get(), ModItems.TIN_TINY_PILE.get(), ModItems.TIN_ORE_DUST.get(),NonNullList.of(ModItems.TIN_DUST.get(), ModItems.TIN_DUST.get(), ModItems.COPPER_TINY_PILE.get(), ModItems.MALACHITE.get(), ModItems.MOON_STONE.get()), ModItems.TIN_PLATE.get(), ModItems.TIN_ROD.get(), ModItems.TIN_GEAR.get(), ModBlocks.TIN_WIRE.get(), ModBlocks.TIN_CABLE.get())),
    BRONZE(new MetalGroup(List.of(Items.COPPER_INGOT, ModItems.TIN_INGOT.get()), List.of(net.minecraft.world.level.block.Blocks.COPPER_BLOCK, ModBlocks.TIN_BLOCK.get()), List.of(ModItems.COPPER_NUGGET.get(), ModItems.TIN_NUGGET.get()), List.of(ModItems.COPPER_DUST.get(), ModItems.TIN_DUST.get()), List.of(ModItems.COPPER_TINY_PILE.get(), ModItems.TIN_TINY_PILE.get()), 3, 1, 4, ModItems.BRONZE_INGOT.get(), ModBlocks.BRONZE_BLOCK.get(), ModItems.BRONZE_NUGGET.get(), ModItems.BRONZE_DUST.get(), ModItems.BRONZE_TINY_PILE.get(), ModItems.BRONZE_PLATE.get(), ModItems.BRONZE_ROD.get(), ModItems.BRONZE_GEAR.get(), null, null)),
    SILVER(new MetalGroup(ModItems.SILVER_INGOT.get(), ModBlocks.SILVER_BLOCK.get(), ModBlocks.SILVER_ORE.get(), ModBlocks.DEEPSLATE_SILVER_ORE.get(), ModItems.RAW_SILVER.get(), ModItems.SILVER_NUGGET.get(), ModItems.SILVER_DUST.get(), ModItems.SILVER_TINY_PILE.get(), ModItems.SILVER_ORE_DUST.get(), NonNullList.of(ModItems.SILVER_DUST.get(), ModItems.SILVER_DUST.get(), ModItems.ALUMINUM_TINY_PILE.get(), ModItems.PLATINUM_TINY_PILE.get()), ModItems.SILVER_PLATE.get(), ModItems.SILVER_ROD.get(), ModItems.SILVER_GEAR.get(), null, null)),
    ELECTRUM(new MetalGroup(List.of(Items.GOLD_INGOT, ModItems.SILVER_INGOT.get()), List.of(net.minecraft.world.level.block.Blocks.GOLD_BLOCK, ModBlocks.SILVER_BLOCK.get()), List.of(Items.GOLD_NUGGET, ModItems.SILVER_NUGGET.get()), List.of(ModItems.GOLD_DUST.get(), ModItems.SILVER_DUST.get()), List.of(ModItems.GOLD_TINY_PILE.get(), ModItems.SILVER_TINY_PILE.get()), 1, 1, 2, ModItems.ELECTRUM_INGOT.get(), ModBlocks.ELECTRUM_BLOCK.get(), ModItems.ELECTRUM_NUGGET.get(), ModItems.ELECTRUM_DUST.get(), ModItems.ELECTRUM_TINY_PILE.get(), ModItems.ELECTRUM_PLATE.get(), ModItems.ELECTRUM_ROD.get(), ModItems.ELECTRUM_GEAR.get(), ModBlocks.ELECTRUM_WIRE.get(), ModBlocks.ELECTRUM_CABLE.get())),
    NICKEL(new MetalGroup(ModItems.NICKEL_INGOT.get(), ModBlocks.NICKEL_BLOCK.get(), ModBlocks.NICKEL_ORE.get(), ModBlocks.DEEPSLATE_NICKEL_ORE.get(), ModItems.RAW_NICKEL.get(), ModItems.NICKEL_NUGGET.get(), ModItems.NICKEL_DUST.get(), ModItems.NICKEL_TINY_PILE.get(), ModItems.NICKEL_ORE_DUST.get(), NonNullList.of(ModItems.NICKEL_DUST.get(), ModItems.NICKEL_DUST.get(), ModItems.PLATINUM_TINY_PILE.get(), ModItems.OPAL.get(), ModItems.BERYLLIUM.get()), ModItems.NICKEL_PLATE.get(), ModItems.NICKEL_ROD.get(), ModItems.NICKEL_GEAR.get(), null, null)),
    INVAR(new MetalGroup(List.of(Items.IRON_INGOT, ModItems.NICKEL_INGOT.get()), List.of(net.minecraft.world.level.block.Blocks.IRON_BLOCK, ModBlocks.NICKEL_BLOCK.get()), List.of(Items.IRON_NUGGET, ModItems.NICKEL_NUGGET.get()), List.of(ModItems.IRON_DUST.get(), ModItems.NICKEL_DUST.get()), List.of(ModItems.INVAR_TINY_PILE.get(), ModItems.NICKEL_TINY_PILE.get()), 2, 1, 3, ModItems.INVAR_INGOT.get(), ModBlocks.INVAR_BLOCK.get(), ModItems.INVAR_NUGGET.get(), ModItems.INVAR_DUST.get(), ModItems.INVAR_TINY_PILE.get(), ModItems.INVAR_PLATE.get(), ModItems.INVAR_ROD.get(), ModItems.INVAR_GEAR.get(), null, null)),
    CONSTANTAN(new MetalGroup(List.of(Items.COPPER_INGOT, ModItems.NICKEL_INGOT.get()), List.of(net.minecraft.world.level.block.Blocks.COPPER_BLOCK, ModBlocks.NICKEL_BLOCK.get()), List.of(ModItems.COPPER_NUGGET.get(), ModItems.NICKEL_NUGGET.get()), List.of(ModItems.COPPER_DUST.get(), ModItems.NICKEL_DUST.get()), List.of(ModItems.CONSTANTAN_TINY_PILE.get(), ModItems.NICKEL_TINY_PILE.get()), 1, 1, 2, ModItems.CONSTANTAN_INGOT.get(), ModBlocks.CONSTANTAN_BLOCK.get(), ModItems.CONSTANTAN_NUGGET.get(), ModItems.CONSTANTAN_DUST.get(), ModItems.CONSTANTAN_TINY_PILE.get(), ModItems.CONSTANTAN_PLATE.get(), ModItems.CONSTANTAN_ROD.get(), ModItems.CONSTANTAN_GEAR.get(), null, null)),
    PLATINUM(new MetalGroup(ModItems.PLATINUM_INGOT.get(), ModBlocks.PLATINUM_BLOCK.get(), ModBlocks.PLATINUM_ORE.get(), ModBlocks.DEEPSLATE_PLATINUM_ORE.get(), ModItems.RAW_PLATINUM.get(), ModItems.PLATINUM_NUGGET.get(), ModItems.PLATINUM_DUST.get(), ModItems.PLATINUM_TINY_PILE.get(), ModItems.PLATINUM_ORE_DUST.get(), NonNullList.of(ModItems.PLATINUM_DUST.get(), ModItems.PLATINUM_DUST.get(), ModItems.GOLD_TINY_PILE.get(), ModItems.ALUMINUM_TINY_PILE.get(), ModItems.MOON_STONE.get()), ModItems.PLATINUM_PLATE.get(), ModItems.PLATINUM_ROD.get(), ModItems.PLATINUM_GEAR.get(), null, null)),
    STEEL(new MetalGroup(List.of(Items.COAL, Items.IRON_INGOT), List.of(net.minecraft.world.level.block.Blocks.COAL_BLOCK, net.minecraft.world.level.block.Blocks.IRON_BLOCK), null, List.of(ModItems.COAL_DUST.get(), ModItems.IRON_DUST.get()), null, 1, 1, 2, ModItems.STEEL_INGOT.get(), ModBlocks.STEEL_BLOCK.get(), ModItems.STEEL_NUGGET.get(), ModItems.STEEL_DUST.get(), ModItems.STEEL_TINY_PILE.get(), ModItems.STEEL_PLATE.get(), ModItems.STEEL_ROD.get(), ModItems.STEEL_GEAR.get(), null, null)),
    LITHIUM(new MetalGroup(ModItems.LITHIUM_INGOT.get(), ModBlocks.LITHIUM_BLOCK.get(), ModBlocks.LITHIUM_ORE.get(), ModBlocks.DEEPSLATE_LITHIUM_ORE.get(), ModItems.RAW_LITHIUM.get(), ModItems.LITHIUM_NUGGET.get(), ModItems.LITHIUM_DUST.get(), ModItems.LITHIUM_TINY_PILE.get(), ModItems.LITHIUM_ORE_DUST.get(), NonNullList.of(ModItems.LITHIUM_DUST.get(), ModItems.LITHIUM_DUST.get(), ModItems.GOLD_TINY_PILE.get(), ModItems.MAGNESIUM_TINY_PILE.get(), ModItems.PERIDOT.get()), ModItems.LITHIUM_PLATE.get(), ModItems.LITHIUM_ROD.get(), ModItems.LITHIUM_GEAR.get(), null, null)),
    MAGNESIUM(new MetalGroup(ModItems.MAGNESIUM_INGOT.get(), ModBlocks.MAGNESIUM_BLOCK.get(), ModBlocks.MAGNESIUM_ORE.get(), ModBlocks.DEEPSLATE_MAGNESIUM_ORE.get(), ModItems.RAW_MAGNESIUM.get(), ModItems.MAGNESIUM_NUGGET.get(), ModItems.MAGNESIUM_DUST.get(), ModItems.MAGNESIUM_TINY_PILE.get(), ModItems.MAGNESIUM_ORE_DUST.get(), NonNullList.of(ModItems.MAGNESIUM_DUST.get(), ModItems.MAGNESIUM_DUST.get(), ModItems.IRON_TINY_PILE.get(), ModItems.ALUMINUM_TINY_PILE.get(), ModItems.TANZANITE.get()), ModItems.MAGNESIUM_PLATE.get(), ModItems.MAGNESIUM_ROD.get(), ModItems.MAGNESIUM_GEAR.get(), null, null)),
    URANIUM(new MetalGroup(ModItems.URANIUM_INGOT.get(), ModBlocks.URANIUM_BLOCK.get(), ModBlocks.URANIUM_ORE.get(), ModBlocks.DEEPSLATE_URANIUM_ORE.get(), ModItems.RAW_URANIUM.get(), ModItems.URANIUM_NUGGET.get(), ModItems.URANIUM_DUST.get(), ModItems.URANIUM_TINY_PILE.get(), ModItems.URANIUM_ORE_DUST.get(), NonNullList.of(ModItems.URANIUM_DUST.get(), ModItems.URANIUM_DUST.get(), ModItems.URANIUM_TINY_PILE.get(), ModItems.COPPER_DUST.get(), ModItems.YELLOW_DIAMOND.get()), ModItems.URANIUM_PLATE.get(), ModItems.URANIUM_ROD.get(), ModItems.URANIUM_GEAR.get(), null, null)),
    LEAD(new MetalGroup(ModItems.LEAD_INGOT.get(), ModBlocks.LEAD_BLOCK.get(), ModBlocks.LEAD_ORE.get(), ModBlocks.DEEPSLATE_LEAD_ORE.get(), ModItems.RAW_LEAD.get(), ModItems.LEAD_NUGGET.get(), ModItems.LEAD_DUST.get(), ModItems.LEAD_TINY_PILE.get(), ModItems.LEAD_ORE_DUST.get(), NonNullList.of(ModItems.LEAD_DUST.get(), ModItems.LEAD_DUST.get(), ModItems.URANIUM_TINY_PILE.get(), ModItems.ALUMINUM_TINY_PILE.get()), ModItems.LEAD_PLATE.get(), ModItems.LEAD_ROD.get(), ModItems.LEAD_GEAR.get(), null, null)),
    ZINC(new MetalGroup(ModItems.ZINC_INGOT.get(), ModBlocks.ZINC_BLOCK.get(), ModBlocks.ZINC_ORE.get(), ModBlocks.DEEPSLATE_ZINC_ORE.get(), ModItems.RAW_ZINC.get(), ModItems.ZINC_NUGGET.get(), ModItems.ZINC_DUST.get(), ModItems.ZINC_TINY_PILE.get(), ModItems.ZINC_ORE_DUST.get(), NonNullList.of(ModItems.ZINC_DUST.get(), ModItems.ZINC_DUST.get(), ModItems.NICKEL_TINY_PILE.get(), ModItems.LEAD_TINY_PILE.get()), ModItems.ZINC_PLATE.get(), ModItems.ZINC_ROD.get(), ModItems.ZINC_GEAR.get(), null, null));
    
    private MetalGroup group;
    
    MetalGroups(MetalGroup group)
    {
        this.group = group;
    }
    
    public MetalGroup getGroup()
    {
        return group;
    }
}
